# This is the default docker compose file that is useful for development
# since it overrides the volumes with local source. Consider using
# docker-compose-deploy.yml for deployments where you don't want the source.
nginx:
  extends:
      file: configs/base.yml
      service: nginx
  links:
    - service:payments-service
  volumes_from:
    - example
    - logs
    - ui

service:
  extends:
      file: configs/base.yml
      service: service
  links:
    - solitude:solitude
  volumes:
    - ./docker/source-links/payments-service/:/srv/payments-service

solitude:
  extends:
      file: configs/base.yml
      service: solitude
  links:
    - mysql:mysql
    - auth:solitude-auth
  volumes:
    - ./docker/source-links/solitude/:/srv/solitude
  working_dir: /srv/solitude
  volumes_from:
    - logs

auth:
  extends:
      file: configs/base.yml
      service: auth
  volumes:
    - ./docker/source-links/solitude-auth/:/srv/auth

mysql:
  extends:
      file: configs/base.yml
      service: mysql
  volumes_from:
    - mysqldata

mysqldata:
  extends:
      file: configs/base.yml
      service: mysqldata

postgres:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres

# FxA storage server.
kinto:
  build: ./docker/source-links/kinto/
  links:
    - postgres:db
  ports:
   - "8888:8888"
  environment:
    CLIQUET_SESSION_URL: postgres://postgres:postgres@db/postgres
    CLIQUET_STORAGE_URL: postgres://postgres:postgres@db/postgres

ui:
  extends:
      file: configs/base.yml
      service: ui
  volumes:
    - ./docker/source-links/payments-ui/public/:/srv/payments-ui

example:
  extends:
      file: configs/base.yml
      service: example
  volumes:
    - ./docker/source-links/payments-example/public/:/srv/payments-example

logs:
  extends:
      file: configs/base.yml
      service: logs
